apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nydus-operator
  name: nydus-operator
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nydus-operator
  template:
    metadata:
      labels:
        app: nydus-operator
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/version: {{ default .Chart.AppVersion .Values.image.tag }}
        app.kubernetes.io/component: operator
        app.kubernetes.io/part-of: "nydus"
        app.kubernetes.io/managed-by: "Helm"
{{- if eq .Values.prometheus.enabled true }}
      annotations:
        prometheus.io/scrape: "{{ .Values.prometheus.enabled }}"
        prometheus.io/port: "{{ .Values.prometheus.port }}"
        prometheus.io/path: "/"
{{- end }}
    spec:
      containers:
      - env:
        - name: MIX_ENV
          value: prod
        - name: BONNY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: BONNY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: BONNY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: BONNY_POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        name: nydus-operator
{{- if eq .Values.prometheus.enabled true }}
        ports:
        - name: metrics
          containerPort: {{ .Values.prometheus.port }}
          protocol: TCP
{{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
      serviceAccountName: nydus-operator
{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
{{- end }}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
