{{- if .Values.injector.enabled -}}
apiVersion: v1
data:
  mutationconfig.yaml: |
    mutationConfigs:
        - name: "nydus-sidecar"
          annotationNamespace: "nydus.kineung.us"
          annotationTrigger: "inject"
          containers: ["nydus"]
  sidecarconfig.yaml: |
    containers:
        - name: nydus
          image: "{{ .Values.injector.nydus.image.registry }}/{{ .Values.injector.nydus.image.repository }}:{{ .Values.injector.nydus.image.tag }}"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5000
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "32Mi"
              cpu: "100m"
          env:
          - name: NYDUS_HOST_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: DEBUG
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.annotations['nydus.kineung.us/debug']
          - name: NYDUS_HTTP_PORT
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.annotations['nydus.kineung.us/http-port']
          - name: SUBSCRIBE_PUBSUB_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.annotations['nydus.kineung.us/subscribe-pubsub-name']
          - name: SUBSCRIBE_TOPIC_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.annotations['nydus.kineung.us/subscribe-topic-name']
          - name: PUBLISH_PUBSUB_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.annotations['nydus.kineung.us/publish-pubsub-name']
          - name: PUBLISH_PUBSUB_TTL
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.annotations['nydus.kineung.us/publish-pubsub-ttl-seconds']
          - name: TARGET_ROOT
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.annotations['nydus.kineung.us/target-root']
          - name: TARGET_HEALTHZ_ADDR
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.annotations['nydus.kineung.us/target-healthz-addr']
          - name: TARGET_VERSION
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.annotations['nydus.kineung.us/target-version']
          - name: INVOKE_TIMEOUT
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.annotations['nydus.kineung.us/invoke-timeout-seconds']
          - name: PUBLISH_TIMEOUT
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.annotations['nydus.kineung.us/publish-timeout-seconds']
          - name: CALLBACK_TIMEOUT
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.annotations['nydus.kineung.us/callback-timeout-seconds']
          - name: DAPR_HEALTHZ_ADDR
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.annotations['nydus.kineung.us/dapr-healthz-address']
          - name: DAPR_HEALTHZ_TIMEOUT
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.annotations['nydus.kineung.us/dapr-healthz-timeout-seconds']
          - name: CLIENT_READ_TIMEOUT
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.annotations['nydus.kineung.us/client-read-timeout-seconds']
          - name: CLIENT_WRITE_TIMEOUT
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.annotations['nydus.kineung.us/client-write-timeout-seconds']
          - name: CLIENT_MAX_CONNS_PER_HOST
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.annotations['nydus.kineung.us/client-maxConnsPerHost']
          - name: CLIENT_HEADER_NORMALIZING
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.annotations['nydus.kineung.us/client-headerNormalizing']
          - name: SERVER_READ_TIMEOUT
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.annotations['nydus.kineung.us/server-read-timeout-seconds']
          - name: SERVER_WRITE_TIMEOUT
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.annotations['nydus.kineung.us/server-write-timeout-seconds']
          - name: SERVER_IDLE_TIMEOUT
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.annotations['nydus.kineung.us/server-idle-timeout-seconds']
          - name: SERVER_HEADER_NORMALIZING
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.annotations['nydus.kineung.us/server-headerNormalizing']
          - name: DEFAULT_TO_STRING
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.annotations['nydus.kineung.us/print-default-tostring']
          - name: XML_TO_STRING
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.annotations['nydus.kineung.us/print-xml-tostring']

kind: ConfigMap
metadata:
  name: nydus-sidecar-injector-configmap
{{- end }}
