{{- if .Values.injector.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: nydus-sidecar-injector
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 8443
      protocol: TCP
      name: https
  selector:
    app: nydus-sidecar-injector
{{- end }}