apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: nydus-operator
  name: nydus-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: nydus-operator
  template:
    metadata:
      labels:
        k8s-app: nydus-operator
    spec:
      containers:
      - env:
        - name: MIX_ENV
          value: prod
        - name: BONNY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: BONNY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: BONNY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: BONNY_POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        image: kineung/nydus-operator:0.1.0
        name: nydus-operator
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 200m
            memory: 200Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
      serviceAccountName: nydus-operator