apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    k8s-app: nydus-operator
  name: externals.nydus.mrchypark.github.io
spec:
  additionalPrinterColumns: []
  group: nydus.mrchypark.github.io
  names:
    kind: External
    plural: externals
    shortNames:
      - ext
      - extl
    singular: external
  scope: Namespaced
  version: v1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    k8s-app: nydus-operator
  name: nydus-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nydus-operator
subjects:
  - kind: ServiceAccount
    name: nydus-operator
    namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: nydus-operator
  name: nydus-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    k8s-app: nydus-operator
  name: nydus-operator
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - '*'
  - apiGroups:
      - nydus.mrchypark.github.io
    resources:
      - externals
    verbs:
      - '*'
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - '*'
---
