operactor:
  enabled: false
  image:
    registry: kineung
    repository: nydus-operator
    tag: ""

  prometheus:
    enabled: false
    port: 9090

  replicaCount: 1
  imagePullPolicy: IfNotPresent
  imagePullSecrets: ""
  nodeSelector: {}
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 200m
      memory: 200Mi

injector:
  enabled: true
  image:
    registry: mrchypark
    repository: generic-sidecar-injector
    tag: "0.4.1"
  nydus: 
    image:
      registry: ghcr.io
      repository: "kineung-us/nydus"
      tag: "0.2.12"

  webhookFailurePolicy: Fail

  replicaCount: 1
  imagePullPolicy: IfNotPresent
  imagePullSecrets: ""
  nodeSelector: {}
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 200m
      memory: 200Mi
