apiVersion: nydus-operator.mrchypark.github.io/v1
kind: External
metadata:
  name: hello-server
  namespace: default
spec:
  nydus:
    debug: "false"
    port: "5000"
    pubsub:
      name: ""
      topic: ""
      ttl: "60"
    target:
      root: ""
      version: "external"
    timeout:
      invoke: "60"
      publish: "5"
      callback: "5"
  dapr: