apiVersion: nydus.mrchypark.github.io/v1
kind: External
metadata:
  name: httpbin
spec:
  metadata:
    annotations:
      # checkout dapr 1.1.0 annotation docs
      # https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-annotations/
      dapr.io/enabled: "true"
      dapr.io/log-as-json: "true"
      dapr.io/log-level: "info"
      dapr.io/sidecar-cpu-limit: 300m
      dapr.io/sidecar-memory-limit: 1000Mi
      dapr.io/sidecar-cpu-request: 100m
      dapr.io/sidecar-memory-request: 250Mi
      prometheus.io/scrape: "true"
      prometheus.io/port: "9090"
      prometheus.io/path: "/"
  nydus:
    http:
      port: "5000" # default set
    publish:
      pubsub:
        name: "pubsub" # required
        ttl: 
          seconds: "60" # default set
    subscribe:
      pubsub:
        name: "pubsub"
      topic:
        name: "httpbin"
    target:
      root: "https://httpbin.org/" # required
      version: "external" # default set
    timeout:
      invoke: 
        seconds: "60" # default set
      publish: 
        seconds: "3" # default set
      callback: 
        seconds: "3" # default set
