image:
  registry: kineung
  repository: nydus-operator
  tag: ""

prometheus:
  enabled: false
  port: 9090

replicaCount: 1
imagePullPolicy: IfNotPresent
imagePullSecrets: ""
nodeSelector: {}
resources:
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 200m
    memory: 200Mi

dapr:
  enabled: false
  global:
    logAsJson: true